config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out:'logout' }, :controllers => {:registrations => 'user_registrations'}
  resources :users
  get 'static_pages/landing_page'

  resources :products
  #get 'static_pages/about'
  get '/products', to: 'products#index'

  get 'static_pages/contact'

  root 'static_pages#landing_page'
  get 'static_pages/index'

  #root 'static_pages#about' #5.1 TEMPORARILY REROUTED TO ABOUT PAGE
  get 'static_pages/about' #5.1 TEMPORARILY REROUTED TO ABOUT PAGE
  get 'logout/index'

  post 'static_pages/thank_you'

  post 'payments/create'

  resources :orders, only: [:index, :show, :create, :destroy]

  resources :products do #a nested resource block
    resources :comments #a nested resource block
  end

  mount ActionCable.server => '/cable'
  
  resources :users #a nested resource block

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability #begin by defining user permissions w the ability class
    include CanCan::Ability

    def initialize(user) #initialize method takes in user obj as a param
        user ||= User.new #guest user (not logged in)
        if user.admin?
        	can :manage, :all
        else
        	can :manage, User, id: user.id
        end
        #can :manage, User, id: user.id #manage is the action to the CAN argument
    end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :product
	scope :rating_desc, -> { order(rating: :desc) }

	validates :body, presence: true
	validates :user, presence: true
	validates :product, presence: true
	validates :rating, numericality: { only_integer: true }
	after_create_commit { CommentUpdateJob.perform_later(self, self.user) }
	
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/product.rb
class Product < ApplicationRecord
	validates :name, presence: true
	
	has_many :comments
	has_many :orders
	def self.search(search_term)
		like_operator = Rails.env.production? ? "ilike" :"LIKE"
		Product.where("name #{like_operator} ?", "%#{search_term}%")
	end

	def highest_rating_comment
		comments.rating_desc.first #capitalized because lowercase C produced an error
	end

	def average_rating
		comments.average(:rating).to_f
	end

	def views
		#$redis.get("product:#{id}")
	end

	def viewed!
		#$redis.incr("product:#{}")
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_many :orders
	has_many :comments
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@product = Product.find(params[:product_id])
		@comment = @product.comments.new(comment_params)
		@comment.user = current_user
		respond_to do |format|
			if @comment.save
				format.html { redirect_to @product, notice: 'Review was created successfully.' } 
				format.json { render :show, status: :created, location: @product }
				format.js
			else
				format.html { redirect_to @product, alert: 'Review was not saved successfully.'}
				format.json { render json: @comment.errors, status: :unprocessable_entity }
			end
		end
		#redirect_to product_path(@product)
	end

	def destroy #adds ability to delete
		@comment = Comment.find(params[:id])
		product = @comment.product
		@comment.destroy
		redirect_to product
	end

private
	def comment_params
		params.require(:comment).permit(:user_id, :body, :rating)
	end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def index
    @orders = Order.includes(:product).all
  end

  def show
  end

  def new
  end

  def create
  end

  def destroy
  end
  
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
	before_action :authenticate_user!

	def create
		@product = Product.find(params[:product_id])
		@user = current_user#PROBLEM HERE???

		token = params[:stripeToken]
		#Create the charge on Stripe servers, this will charge the user's card
		begin
			charge = Stripe::Charge.create(
				amount: (@product.price).to_i,
				currency: "usd",
				source: token,
				description: params[:stripeEmail],
				receipt_email: params[:stripeEmail]
			)

			if charge.paid
				Order.create!(product: @product, user: @user, total: @product.price )
				UserMailer.receipt_email(@user).deliver_now
				flash[:alert] = "Your payment was successful"
			end

		rescue Stripe::CardError => e
			#The card has been declined
			body = e.json_body
			err = body[:error]
			flash[:error] = "There was an error processing your payment: #{err[:message]}"
		end

		redirect_to product_path(@product)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!#to make sure user is signed in first
  load_and_authorize_resource#ensures user is authorized to perform action

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name)
    end
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_form_helper.rb
module ContactFormHelper
end

app/helpers/controllers_helper.rb
module ControllersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
	def cache_key_for_products
		count = Product.count
		max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number) 
		"products/all-#{count}-#{max_updated_at}"
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/thank_you_helper.rb
module ThankYouHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewApp</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <link href="https://fonts.googleapis.com/css?family=Megrim" rel="stylesheet">
  </head>

  <body>
    <div id="wrapper">

      <!--==========-->
      <!--NAVIGATION-->
      <!--==========-->
  	 <nav class="navbar navbar-default navbar-fixed top navbar-collapse">
      <div class="container">
  		  <ul>
         <li><%= link_to 'Products', products_path %></li>
  			 <li><%= link_to 'About', static_pages_about_path %></li>
  			 <li><%= link_to 'Contact', static_pages_contact_path %></li>
         <li>
         <%= form_with(url: products_path, method: 'get', local: true) do |form| %>
          <%= form.label :q, 'Search for:' %>
          <%= form.text_field :q, id: 'q', value: params[:q] %>
          <%= form.submit 'Search' %>
          <% end %>
          </li>
  		  </ul>
        <ul class="nav pull-right">
          <li>
            <% if user_signed_in? %>
              <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
            <% else %>
              <%= link_to('Login', new_user_session_path) %>
            <% end %>
          </li>
        </ul>
        <h1 id="bb"><a href="#">BB</a></h1>

      </div><!--end the navigation bar container-->
  	 </nav>


     <% if notice %>
      <p id="notice" class="alert alert-info"><%= notice %></p>
     <% end %>

      <% if alert %>
        <p id="alert" class="alert alert-danger"><%= alert %></p>
      <% end %>


      <%= yield %>

      <footer class="container">
        <div class="footer">
    	   <p>&copy; 2017 Bike Berlin</p>
        </div>
      </footer>

      </div><!--end wrapper div-->
    
  </body>
</html>

app/views/shared/_stripe_checkout_button.html.erb
<script 
	src="https://checkout.stripe.com/checkout.js" class="stripe-button"
	data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
	data-image="<%= @product.image_url %>"
	data-name="<%= @product.name %>"
	data-description="<%= @product.description %>"
	data-amount="<%= @product.price %>">
</script>